version: '3.8'

services:
  postgres:
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    command: ["postgres", "-c", "listen_addresses=*"]
    entrypoint: ["/bin/bash", "-c", "docker-entrypoint.sh postgres & sleep 5 && psql -U postgres -d postgres -tc \"SELECT 1 FROM pg_database WHERE datname = 'notification_service'\" | grep -q 1 || psql -U postgres -d postgres -c 'CREATE DATABASE notification_service;' && psql -U postgres -d postgres -tc \"SELECT 1 FROM pg_database WHERE datname = 'notification_service_test'\" | grep -q 1 || psql -U postgres -d postgres -c 'CREATE DATABASE notification_service_test;' && wait"]

  localstack:
    image: localstack/localstack:latest
    ports:
      - 4566:4566

volumes:
  postgres_data:
    driver: local
