services:
  postgres:
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: notification_service
    ports:
      - 5432:5432

  localstack:
    image: localstack/localstack:latest
    ports:
      - 4566:4566