name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven

    - name: Build DB and Localstack
      run: docker-compose build
          
    - name: Start DB and Localstack
      run: docker-compose up -d
    
    - name: Set up SQS queues
      run: |
          export SQS_ENDPOINT=http://localhost:4566
          aws --endpoint-url=$SQS_ENDPOINT sqs create-queue --queue-name update-status
          aws --endpoint-url=$SQS_ENDPOINT sqs create-queue --queue-name sending-email-queue
          aws --endpoint-url=$SQS_ENDPOINT sqs create-queue --queue-name sending-sms-queue
          aws --endpoint-url=$SQS_ENDPOINT sqs create-queue --queue-name sending-push-queue
          aws --endpoint-url=$SQS_ENDPOINT sqs create-queue --queue-name sending-whatsapp-queue

    - name: Build with Maven
      run: mvn clean install -P dev -DskipTests
        
  test:
    runs-on: ubuntu-latest
    needs: build
          
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run tests
        run: mvn test -P test
        
