name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven

    - name: Debug Java Version
      run: java -version

    - name: Start Database and Localstack
      run: docker-compose up -d

    - name: Wait for database to be ready
      run: sleep 10

    - name: Set up SQS queues
      run: |
          export SQS_ENDPOINT=http://localhost:4566
          export AWS_REGION=us-east-1
          export AWS_ACCESS_KEY_ID=fake
          export AWS_SECRET_ACCESS_KEY=fake
          export AWS_SESSION_TOKEN=fake

          aws --endpoint-url=$SQS_ENDPOINT --region $AWS_REGION sqs create-queue --queue-name update-status
          aws --endpoint-url=$SQS_ENDPOINT --region $AWS_REGION sqs create-queue --queue-name sending-email-queue
          aws --endpoint-url=$SQS_ENDPOINT --region $AWS_REGION sqs create-queue --queue-name sending-sms-queue
          aws --endpoint-url=$SQS_ENDPOINT --region $AWS_REGION sqs create-queue --queue-name sending-push-queue
          aws --endpoint-url=$SQS_ENDPOINT --region $AWS_REGION sqs create-queue --queue-name sending-whatsapp-queue

    - name: Build with Maven
      run: mvn clean install -Pdev -DskipTests

  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven

    - name: Debug Java Version
      run: java -version

    - name: Start Database and Localstack
      run: docker-compose up -d

    - name: Wait for database to be ready
      run: sleep 10

    - name: Run tests
      run: mvn clean -Ptest test
